### PR TITLE
Bug-fixes by Zac

### LINKED ISSUE #45: Less-than sign breaks auto-rename
This is really annoying when you use PHP code in your tags.

## Code:
```HTML
<div title="<?php echo "FOO"?>">
</div>

<span title="<">
</span>
```

### LINKED ISSUE #49: Using delete key causes problems
Using the delete key instead of backspace causes weird behaviour

unnesteddelete

Also if you do that in a nested table, it gets even worse (note the parent `<t>` tags)

delete

Potentially related to https://github.com/formulahendry/vscode-auto-rename-tag/issues/12

### LINKED ISSUE #65: Inappropriate result using accent
When starting a React (.jsx) component named "Título", the final tag renamed only the "T" by stopping in the "í" accent.

captura de tela 2018-08-02 as 14 01 15

I'm not sure if this is another bug, but if you are using a tag with accent the auto rename stop to work. I renamed "Título" to "TESTE" and last tag didn't change.

captura de tela 2018-08-02 as 14 07 28

### LINKED ISSUE #67: Doesn't seem to work when leading character is an underscore
Title says it all. :)

### PR DESCRIPTION
**Pull request by Zaczero**
Fixed #67 
Fixed #65 
Fixed #49 
Fixed #45
I've been testing the extension mod for some time on my projects and didn't face any 'new' bugs caused by those changes so I think it's pretty stable ☺️

### CODE REVIEW

**Comment by rienheuver** [comment]
Why isn't this merged yet?

**Comment by Zaczero** [comment]
@rienheuver I guess this project is abandoned by the owner :/

**Comment by dzienisz** [comment]
Please merge! @formulahendry

**Comment by kokoshneta** [comment]
Is this still not merged? Is the project just completely abandoned by the owner? :-/

**Comment by formulahendry** [comment]
Thanks @Zaczero !

**Pull request merged**
